### ISSUE TITLE
Modal window doesnt work on chrome

### ISSUE THREAD

**Issue by silentwarrior** [radogado/natuive#15]
Hello.

The modal window doesnt work on chrome in your "live" page.

**Comment by radogado** [comment]
Hi @silentwarrior, thanks for the report. It seems to work on Chrome on Mac and Windows XP. Which system are you using? Regards.

**Comment by silentwarrior** [comment]
I have both Safari, Chrome, Firefox and Opera on Macosx 10.9 and 10.10 now.

In none of them it works, after clicking on it I only see a transparent black navbar show up on the top, but the page itself never changes nor I see any modal.

**Comment by silentwarrior** [comment]
Let me just ask, it may be a dumb question but, is the modal you refer to a full page clone of the website?

**Comment by radogado** [comment]
Hi @silentwarrior, the modal window works. You might be confused, because the content in the modal window is taken from the same HTML page and that's why it looks the same. If you see the black bar on top, it meant you have a modal window opened. Thanks.
