### ISSUE TITLE
Autosliding stop functioning after manual sliding

### ISSUE THREAD

**Issue by amiroff** [radogado/natuive#16]
First of all, great job!

Having data-autoslide="x" on slider, it starts autosliding. But after manually switching some slides autosliding stops. Confirmed on up-to-date version too. JS console hints: Uncaught TypeError: Cannot set property 'onchange' of null.

**Comment by radogado** [comment]
Hi @amiroff thanks, the idea is that once the user starts interacting with a slider, he should be in control. Auto-sliding afterwards would take control out of the user, which I think isn't good UX. The console error shouldn't happen and I'm not reproducing it here, what browser/platform are you on? Regards.
