### ISSUE TITLE
Microsoft demo page broken on small Chrome screen

### ISSUE THREAD

**Issue by naasking** [radogado/natuive#17]
If you shrink the Chrome window to its smallest horizontal size, the mobile menu that appears at the top incorrectly overflows to the next line. I assume of course it's supposed to be right-aligned at the top like every other mobile site.

**Comment by naasking** [comment]
Also the slideshow text overlaps the images on smaller screens.

**Comment by radogado** [comment]
Hi @naasking, I didn't have enough time to spend on the mobile version and the overlapping text on smaller screens is seen on the original MS site. Regards.
