### ISSUE TITLE
Demo pages should not have minified HTML

### ISSUE THREAD

**Issue by naasking** [radogado/natuive#18]
Looks you have an interesting framework here. Featureful yet compact. The demo pages are a good modulo a few small bugs, but prospective users can't get a feel for natUIve just by viewing the source of those pages because the HTML is minfied.

**Comment by radogado** [comment]
Hi @naasking please check the GitHub-hosted unminified demos: http://radogado.github.io/natuive/
There is also documentation about the HTML structure.
Thanks.
