### ISSUE TITLE
Can't close tooltip on touch devices

### ISSUE THREAD

**Issue by naasking** [radogado/natuive#19]
If you view the demo page natuive.net on a touch device, and click the toolip text, the tooltip does indeed show up, but there's no way to get rid of it.

**Comment by radogado** [comment]
Thanks @naasking doesn't always work and I will look into it.

**Comment by naasking** [comment]
Oh, and it the ? icon doesn't show up on those small screens either, I had to click the text.

**Comment by radogado** [comment]
Thank you, added to the to-do list. Cheers.

**Comment by naasking** [comment]
The ? icon now shows up, and the close button works, but touches pass through to the content underneath. So if I touch the ?, I see the tooltip, and if I touch "Here is the tooltip" or the first "Lorem ipsum" it goes away, but if I touch the second "Lorem ipsum" it actually opens the "Open a modal window" link inside a new tab.

So that's the wrong behaviour for the tooltip and the modal window.

**Comment by radogado** [comment]
Thanks for the through test @naasking you are right there is an issue and I'll look into it. Cheers.

**Comment by radogado** [comment]
Fixed by removing the touch handler on the tip (popup), only opening/closing by ?/X and the tool text.
