### ISSUE TITLE
Lightbox overflows to next line on small device

### ISSUE THREAD

**Issue by naasking** [radogado/natuive#20]
I'm not sure what the intent is on the features page, but on a mobile device the images of the lightbox don't show up on a single row, they overflow to the next line.

It displays correctly on a shrunk Chrome window on a desktop, just not on the mobile device.

**Comment by radogado** [comment]
Hello @naasking, the images all available space and wrap on further lines. Imagine 10+ images. I think that's natural behavior, what would you suggest? Thanks.
