### ISSUE TITLE
Grid layout is broken on demo

### ISSUE THREAD

**Issue by dotnetchris** [radogado/natuive#22]
http://radogado.github.io/natuive/#grid shows lines clipping out the left side while leaving gaps on the right side. 

http://imgur.com/0eTYfF0

**Comment by radogado** [comment]
Thanks for pointing out this Firefox bug @dotnetchris, it's fixed now. Regards.

**Comment by dotnetchris** [comment]
FWIW i saw the same in chrome 48 or 49. I don't know which version mine is, mine updated but hasn't restarted yet.

**Comment by radogado** [comment]
Hi, checked Chrome 49 on Mac and Windows and can't reproduce it. Cheers
