### ISSUE TITLE
Some file Paths are way too long...

### ISSUE THREAD

**Issue by SalvorinFex** [radogado/natuive#23]
I am on Windows 10 and I can Not Clone your repo.

![screenshot 2016-08-07 23 25 31](https://cloud.githubusercontent.com/assets/2433369/17471089/6b38e37e-5cf6-11e6-9730-bdf8a03b544f.png)

This was not an issue about 4 to 6 months ago, when I last Cloned it.

**Comment by radogado** [comment]
Hi @SalvorinFex sorry about that. I need Node for Grunt and will think of a solution for both Grunt and Windows 10 clone to work. Thanks for the notice.

**Comment by radogado** [comment]
node_modules now ignored by git and there are no overlong paths in the repo. Regards

**Comment by SalvorinFex** [comment]
Alright, Thanks, I will try Cloning it again.
