### ISSUE TITLE
An Example for starting a conversion...

### ISSUE THREAD

**Issue by SalvorinFex** [radogado/natuive#24]
More of a request for a little help than an Issue.

I am going to convert this site:  [Petteys Auto Service](http://petteysrb.com/) to responsive using your Framework.
It seems like a good fit and I have been waiting until a project came up to try it on.
I just need a little starter help, an example of the home page, just part of it would suffice.

Then I can use the example to finish converting the rest of the site on my own.

I would greatly appreciate this!

**Comment by radogado** [comment]
Hi @SalvorinFex, here is the home page: https://drive.google.com/open?id=0B0jG0kU-SWi0WEZyTnktZ2tzRkU

I just followed the general steps for making a new page:

1. duplicate the dist folder and edit index.html
2. create a new css file and add it to <head>
3. break down the design as a grid with columns
4. add the content
5. customise style

This site would need the top graphics to be separated in columns for better alignment with the main content.

Good luck. Regards,
Rado

**Comment by SalvorinFex** [comment]
Thank you, that's a great starting point!!

THe client likes it and I would like to fix the fonts and spacing still.

**Comment by SalvorinFex** [comment]
Hey there, My system has been down with some Win 10 issues.
I would change the font settings, I have edit the CSS pages but that doesn't seem to change the font sizes or the spacing.

How would I go about that?

**Comment by radogado** [comment]
Hello, the page uses the combined/minified CSS file, not the source files. It's best to add a new CSS file with your new properties like body font etc.
Regards,

**Comment by SalvorinFex** [comment]
Hi, Me again.
Is it possible to, on only the mobile page parts on this site, to push the page to the bottom of the screen, so the menu is there but you'd need to scroll up to it, instead of scrolling down to the content?

http://avernon.net/petteys/petteys/

**Comment by radogado** [comment]
Hello again, a quick solution would be to swap the order of the nav and main content:

```
@media screen and (max-width: 640px) {

	main > .row > :first-child {
		
		order: 1;
		
	}

}
```

Regards.
