### ISSUE TITLE
Cloning in Github Desktop...

### ISSUE THREAD

**Issue by SalvorinFex** [radogado/natuive#25]
Hello, 

I have tried over the last few weeks to clone or re-clone this repo, with Github desktopbut it keeps erroring out.

I have one log here, from one of my systems and can create others if necessary. 

https://dl.dropboxusercontent.com/u/30598156/GitHubLog.txt

**Comment by radogado** [comment]
Hi, sorry about GitHub Desktop for Windows problems. I don't use it and currently have no solution.
In the meantime, you can get the minified code from:
https://radogado.github.io/natuive/dist/natuive.min.css
https://radogado.github.io/natuive/dist/natuive.min.js

Regards.
