### ISSUE TITLE
Problems scaling at 640px or less

### ISSUE THREAD

**Issue by naasking** [radogado/natuive#26]
Many demo pages have problems once you scale the viewport below 640px. For instance, the drop downs in the menu on the Microsoft page stop working.

The Pebble demo has problems as well, namely the Buy Now/Learn More links snap to the top underneath the Pebble heading from the navbar.

The Tesla heading gets weird too. Just trying to give some constructive feedback for an ambitious project!

**Comment by radogado** [comment]
Thanks you @naasking for identifying these accessibility issues, to be fixed ASAP. Cheers!

**Comment by naasking** [comment]
I don't want to create an issue for this, so just some suggestions:

1. I'm not a front-end guy, but I dabble from time to time. Since your project description mentions semantic markup, you might want to make your tab interface more semantically meaningful, along these lines: https://higherlogics.blogspot.ca/2016/11/semantic-tab-panels-via-html-tables.html
2. Also, the PDF document describing your classes doesn't seem complete, and I found it difficult to follow. Your demo pages are a little better, but reference docs the way UIKit and Bootstrap explain their core and the components would be much better IMO.

**Comment by naasking** [comment]
Looks like you're making changes, so here's a regression: the demo site http://natuive.net/  on desktop Chrome and FF now renders horizontal and vertical scrollbars around the top hamburger/navbar when the viewport is scaled below 640px.

**Comment by radogado** [comment]
Hi @naasking you are right, those things need to be fixed. Thanks.

**Comment by radogado** [comment]
Microsoft drop nav fixed, it had outdated markup, thanks for the notice.
