### ISSUE TITLE
Slider on mobile

### ISSUE THREAD

**Issue by naasking** [radogado/natuive#27]
The slider on your [demo page](https://radogado.github.io/natuive/) doesn't quite render properly on my Nexus 5. The slider buttons actually overlap the content instead of appearing below (for the numbers) and beside it (for the arrows), as expected.

In portrait mode on mobile, the content of the first slide is only one line, so the buttons used to move to the next/prev slide are cut off, almost to the point where you can't see them.

**Comment by radogado** [comment]
Added optional **.slider.pad** class to display controls outside the slider.

**Comment by naasking** [comment]
Nav buttons in the slider are no longer cut off. Is there a way to position those nav buttons based on the largest markup so they don't jump around all the time when switching slides?

**Comment by radogado** [comment]
Yes, that is the normal behaviour unless **.slider.auto-height** is used. It's a bug in Chrome and I'll fix it. Thanks.
