### ISSUE TITLE
Fixed background on mobile

### ISSUE THREAD

**Issue by naasking** [radogado/natuive#28]
The fixed background of your mobile page actually moves on my Nexus 5. I'm not sure what it's doing exactly, because it's not scrolling while I scroll, it looks like it's resizing the background based on how much of the image is in the viewport. It's most noticeable if you scroll quickly up and down before/after the point where 50-60% of the image is visible.

**Comment by radogado** [comment]
When scrolling, the browser nav bar appears and disappears, changing the viewport dimensions and pushing the fixed background. It's an old, tricky mobile problem and I need to think of a solution. Thanks.
