### ISSUE TITLE
Drop menu/hamburger behaviour on mobile

### ISSUE THREAD

**Issue by naasking** [radogado/natuive#30]
On my Android browser, the hamburger drop menu behaves a little strangely. If you expand the hamburger, tap one of the menu items it expands as expected. If you tap one of the other menu items, it collapses the previous one and expands the new one. That's all good.

But if you then tap the already expanded menu item, it collapses the whole menu back into the hamburger, which is surprising. I expected the expanded menu to collapse but leave the hamburger open.

**Comment by radogado** [comment]
Hi, can't reproduce it on Android Chrome. Are you using the old Android Browser? Thanks.

**Comment by naasking** [comment]
Ah, the problem I described is on natuive.net, not on your non-minified demo page. I suppose that the minified site contains older code and markup. Probably a few of the issues I created are related to this, so I'll go through them again.

**Comment by radogado** [comment]
Finally updated **natuive.net**. I need to create an easy automatic update process... Thanks again.
