### ISSUE TITLE
Google design page displays unresponsponsive hamburger on mobile

### ISSUE THREAD

**Issue by naasking** [radogado/natuive#31]
On my mobile device, the [Google design page](https://radogado.github.io/natuive/demos/google-design/) shows a hamburger menu even though the full menu is already expanded. The Hamburger does not respond to touches.

**Comment by radogado** [comment]
Will hide the mobile nav behind a burger. Thanks!

**Comment by naasking** [comment]
This issue is the same as other issues: difference between natuive.net and non-minified demo. On natuive.net, the hamburger shows up but does nothing as described in this issue. It does not show up on non-minified demo. Sorry for all the confusion!

**Comment by radogado** [comment]
Added burger to Google Design nav.
