### ISSUE TITLE
Missing demo pages on mobile

### ISSUE THREAD

**Issue by naasking** [radogado/natuive#32]
On my Android browser, the Tesla demo page is the last one that shows up in your demo page's showcase. I can't see the Amnesty, Stripe or Star Wars demos. I can see them on a scaled desktop browser, so it's a mobile issue only, and I don't see any annotations in the markup that explicitly exclude it on mobile.

**Comment by radogado** [comment]
Tested on Moto G Chrome and those demos are visible. Could have been a network issue. Regards.

**Comment by naasking** [comment]
This issue is because I was browsing natuive.net on my phone, which differs from the non-minified page. I suggest keeping natuive.net up to date with the non-minified page to avoid confusion, or perhaps remove the natuive.net link from the main set of links on the github page. Maybe move it down to where you describe the releases and let user know natuive.net is running the last official release or something.
