### ISSUE TITLE
Click this copy button doesn't work

### ISSUE THREAD

**Issue by naasking** [radogado/natuive#33]
The "Click this copy button to copy the contents of the above paragraph to the clipboard" doesn't work. I get the following error on Chrome:

    natuive.js:1323 Discontiguous selection is not supported.(anonymous function) @ natuive.js:1323

It happens every time if, with the mouse, you select some of the text in this same paragraph, like "copy the contents", then click the button.

**Comment by radogado** [comment]
Indeed Chrome needs a selection, while it works in Safari. Added to list. Thanks.

**Comment by radogado** [comment]
Tested and working in Chrome.
