### ISSUE TITLE
Undocumented markup

### ISSUE THREAD

**Issue by naasking** [radogado/natuive#35]
If you don't mind, I'd like to use this ticket as a central place to list features which aren't documented or explained sufficiently.

1. Drop down nav: this seems to require quite a bit of extra, non-semantic markup which isn't explained at all. For instance, under the `<nav>` element, there are immediately two `<form>` elements with classes level1 and level2, and each child list element has a reset and a radio input. I'm not sure what purpose these serve. Is it some kind of non-JS/pure-CSS fallback behaviour?
2. Android browser scroll polyfill: this isn't really explained, but obviously addresses some deficiency in some unspecified Android browser version. I recommend adding the Android browser version that exhibits this problem, although just applying the polyfill automatically instead of needing to opt-in would be ideal.
3. The drop-cap class has no explanation. I believe this increases the size of the first letter of the first word given the demo page.
4. There's no example from scrollable nav on the demo page and no explanation.
5. No example for span-relative-parent which you list under "Links" in the pdf doc.

**Comment by radogado** [comment]
Hi @naasking,

1. Yes, it's for CSS-only functionality using the form reset function to close the active item.
2. It's the **Overthrow** polyfill for scrolling anything other than the body in **Android Browser**. That's the name of the old browser before **Chrome**. Added a note to the doc.
3. Sorry, thought it was obvious. Added a short description to the doc.
4. Added explanation and an example.
5. Added a sample parent-spanning link.

Thanks for the notices. I have a new documentation + demo page in the works, and it should provide a much clearer outlook.

Regards!
