### ISSUE TITLE
Customer burger symbol

### ISSUE THREAD

**Issue by naasking** [radogado/natuive#37]
Looks like the burger symbol is hard-coded into the css. This doesn't seem necessary since you can just use whatever character the user wants inside the span:

    <span class="burger">&bull;&bull;&bull;</span>

**Comment by radogado** [comment]
Hi, you can put anything inside **div.label**, it doesn't have to be **span.burger**:

```
<header class="fold mobile">
			
	<div class="label"> 
		
		<span>Custom</span> 
		
	</div>

	<div class="content">
		
		...

	</div>

</header>
```
